version: "3.1"
services:
  mysql-dev:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: olya1110
      MYSQL_DATABASE: pets_project
    ports:
      - 3307:3306
    volumes:
      - mysql-dev:/tmp

volumes:
  mysql-dev:
    external: false